CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(75) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS Country (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS State_address (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(150) NOT NULL,
    fk_country INTEGER NOT NULL,
    FOREIGN KEY (fk_country) REFERENCES Country(id)
);

CREATE TABLE IF NOT EXISTS City (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(150) NOT NULL,
    fk_state INTEGER NOT NULL,
    FOREIGN KEY (fk_state) REFERENCES State_address(id)
);

CREATE TABLE IF NOT EXISTS User_address (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    latitude DECIMAL(8, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    fk_user INTEGER NOT NULL,
    fk_city INTEGER NOT NULL,
    FOREIGN KEY(fk_user) REFERENCES User(id),
    FOREIGN KEY(fk_city) REFERENCES City(id)
);